[package]
name = "opt_args"
version = "0.1.0"
authors = ["BeLZeL"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3" }
