[package]
name = "redis"
version = "0.1.0"
authors = ["BeLZeL"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = {version = "*"} # https://docs.rs/redis/0.20.1/redis/

#[dependencies.redis]
#version = "*"
