# ansible-playbook localhost_fill_tmp_file.yml
---
- name: This is a hello-world example
  hosts: localhost
  tasks:
  - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
    copy: content="hello world\n" dest=/tmp/testfile.txt